Netflix/weep

cmd/ecs_credential_provider.go
cmd/metadata.go
cmd/root.go
go.mod
go.sum
main.go

This PR adds support for running weep as a service using [`kardianos/service`](https://github.com/kardianos/service). This should work on Windows, Linux, and macOS. Interactive CLI use is unaffected.
Fixes #28

Add support to run weep as a service

---

cmd/file.go
cmd/vars.go

Add a `--refresh`/`-R` flag to `weep file` to enable auto-refresh of file credentials. When enabled, weep will check the credentials every minute and refresh them if the expiration is within 10 minutes.

feat: Add credential refresh to file mode

---

cmd/ecs_credential_provider.go
cmd/metadata.go
handlers/healthcheckHandler.go
health/health.go

This PR adds the mechanisms for an HTTP healthcheck endpoint. It currently returns `200 OK` no matter what. Handling of unhealthy states will be handled in subsequent PRs.

Add HTTP healthcheck endpoint

---

handlers/middleware.go
handlers/middleware_test.go

- Don't allow an empty host header
- Add `localhost` to allowed hosts
- Deny presence of `Referrer` or `Origin`, even if set to an empty value
- Add test cases for the above and DRY up test file

Tweak browser filter denials

---

.github/workflows/release.yml
.goreleaser.yml
weep-demo.yaml

This PR adds a goreleaser build config to compile binaries with a built-in configuration for the [ConsoleMe OSS demo site](https://demo.consolemeoss.com). Resulting binaries are uploaded to an S3 bucket.

Add release logic for demo site binary

---

cmd/completion.go
cmd/credential_process.go
cmd/docs.go
cmd/ecs_credential_provider.go
cmd/file.go
cmd/metadata.go
cmd/root.go
cmd/service.go
config/config.go
creds/aws.go
creds/consoleme.go
creds/refreshable.go
handlers/baseHandler.go
handlers/credentialsHandler.go
handlers/ecsCredentialsHandler.go
handlers/healthcheckHandler.go
handlers/iamInfoHandler.go
handlers/instanceIdentityDocument.go
handlers/middleware.go
logging/logger.go
mtls/mtls.go
util/util.go

Add a `logging` package to tuck away logging initialization and configuration, then call `logging.GetLogger()` to create a package-level `log` variable that drops in for the old logrus alias.

Simplify logging setup

---

.github/workflows/precommit.yml
.github/workflows/release.yml
go.mod
go.sum

Upgrade Go to 1.16, which _should_ automatically convince goreleaser to build darwin/arm64 binaries for Apple Silicon.

Upgrade Go to 1.16

---

cache/cache.go
cmd/serve.go
config/config.go
creds/refreshable.go
example-config.yaml
httpAuth/mtls/mtls.go
server/server.go
weep-demo.yaml

- Fix FD leak by reusing TLS configuration across clients
- Update config key for server port, add server address to config
- Remove AWS credential provider retries so we can return a helpful error instead of the SDK timing out
- A bit of logging housekeeping

Reuse TLS config to avoid FD exhaustion

---

creds/refreshable.go

The `RefreshableProvider` initializer incorrectly uses the `role` parameter (which is typically a role ARN) as the `Role` field, which should just be the role name.

Correctly set Role and RoleArn in RefreshableProvider

---

cache/cache.go
cache/cache_test.go
creds/refreshable.go
creds/refreshable_test.go
creds/types.go
server/credentialsHandler.go

Following up on #55, `RefreshableProvider.Role` was incorrectly being used to request credentials from ConsoleMe. This PR fixes that and renames some fields to be more intuitive.

Use RoleArn for RefreshableProvider requests

---

cmd/service.go
config/config.go
example-config.yaml

Allow the service command to be configured with flags separated from args to avoid problems with flags being interpreted as args.

Add separate config for service flags

---

config/config.go
server/credentialsHandler.go
server/server.go

Weep was creating `tmp/weep.log` in its working dir, which is annoying and bad.
This PR also adds support for no trailing slash on the `/latest/meta-data/iam/security-credentials` endpoint to match the behavior of IMDS.

Fix default log dir, endpoint trailing slash tweak

---

cmd/root.go
go.sum
main.go

Currently, the error is printed twice, as cobra already prints it out. This PR ensures the error is only printed once.
Before:
After:

Only print out the error once

---

creds/consoleme.go

In cases where ConsoleMe is configured to use mutual TLS, the API and web interface may be served from different URLs. This PR adds the ability to override the `consoleme_url` config entry with `consoleme_open_url_override` for the purpose of generating URLs for the `open` command.

Allow URL override for `open` links

---

go.mod
go.sum
httpAuth/mtls/certificate.go

In the case where the mTLS file watcher creation returns an error, Weep would crash due to a nil pointer dereference. This PR returns after logging the error to prevent this crash.

Return on mTLS watch error to avoid nil pointer deref

---

errors/errors.go
util/util.go

This PR prevents Weep from automatically opening browser windows using the `weep open` command on Windows platforms due to an edge case that can lead to command injection. This will be re-enabled when we have a good approach for sanitizing input to the `OpenLink()` function.

Disable browser open on Windows

---

cmd/root.go
cmd/serve.go
example-config.yaml

This PR changes how Weep handles CLI flags that can also be set in the configuration file to fix an issue where configuration settings are not correctly handled when running Weep as a system service.

Bind CLI flags to config keys

---

httpAuth/mtls/mtls.go

This PR makes Weep no longer require the mTLS cert, key, and trust store to be in the same directory.

allow mTLS cert/key/trust store to be in any configured dirs

---

cmd/credential_process.go
cmd/file.go
util/util.go

Automatically create directory/directories when writing files with the `file` and `credential_process` commands, a la `mkdir -p`. This PR also changes the file permissions to more closely match those that are set by awscli.
Fixes #70

fix: Create directory for file and credential_process commands

---

cmd/credential_process.go

Fix a minor missing check that causes a runtime panic, instead of displaying an appropriate error.
Command: `weep credential_process`
Previous output:
```
panic: runtime error: index out of range [0] with length 0
goroutine 1 [running]:
github.com/netflix/weep/cmd.runCredentialProcess(0x1c5acc0, 0x1c93cf0, 0x0, 0x0, 0x0, 0x0)
/Users/Jay/go/src/github.com/netflix/weep/cmd/credential_process.go:107 +0x125
github.com/spf13/cobra.(*Command).execute(0x1c5acc0, 0x1c93cf0, 0x0, 0x0, 0x1c5acc0, 0x1c93cf0)
/Users/Jay/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0x1c58c40, 0xc00029ff28, 0x3, 0x3)
/Users/Jay/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...) …
```

Fix runtime panic due to missing argument

---

cmd/list.go

Address #73 by setting output to for the `Print` command before calling the `Print` command. Currently, since we don't set the output, it goes to stderr by default. This will explicitly set the output to go to stdout.

Address #73

---

cmd/list.go

Cobra's `cmd.SetOut()` apparently doesn't affect `cmd.Print()`, but does affect `cmd.Println()`. This PR double fixes #73.

Print role list to stdout

---

cmd/helpers.go

Allows user to search by role name, account friendly name, account number

Improve search experience for commands such as file, export

---

pkg/reachability/channels.go
pkg/reachability/request.go
pkg/server/healthcheckHandler.go
pkg/server/server.go

This PR proposes a reachability test previously described on issue #74
Adds a package with the capability of attempting to reach the IMDS serve, while also determining whether that Weep instance has received this test on the other side of the wire
Uses that package on `weep serve` and on the healthcheck route.
Demo:

Reachability test

---

cmd/completion.go
cmd/docs.go
cmd/file.go
cmd/root.go
cmd/serve.go
cmd/service.go
pkg/httpAuth/mtls/certificate.go
pkg/httpAuth/mtls/mtls.go
pkg/server/server.go

We've been unnecessarily using the `Fatal()` and `Fatalf()` log functions for things that don't actually need to be fatal. This switches a lot of those to `Error()` and `Errorf()`, respectively, or returns errors to be handled at a higher level where possible.

Remove calls to Fatal log functions

---

cmd/service.go

This PR fixes the service configuration when `service.args` are specified in the config file used when `weep service install` is run.

Remove service.args from service configuration

---

cmd/service.go

This PR adds some extra options to the service installation that will configure the Windows service to restart on failures.

Restart Windows service on failure

---

cmd/list.go
cmd/root.go
cmd/vars.go
pkg/config/config.go

Allows the user to specify an extra config file at runtime by using the argument `--extra-config-file /path/to/file.yaml`

Allow extra config file

---

pkg/config/config.go
pkg/creds/consoleme.go

This PR allows for customizing the ConsoleMe HTTP client creation and request building workflows when using Weep as a library.

Add support for custom HTTP client & preflight

---

cmd/credential_process.go
cmd/helpers.go
cmd/list.go
cmd/open.go
pkg/creds/consoleme.go
pkg/httpAuth/custom/custom.go
pkg/httpAuth/httpAuth.go
pkg/server/ecsCredentialsHandler.go
pkg/server/server.go
pkg/swag/swag.go

A quick revision to #112. This PR moves more into the `httpAuth` package and adds the custom stuffs to `httpAuth.custom`.

Refactor HTTP client creation to be more generic

---

pkg/creds/refreshable.go
pkg/httpAuth/mtls/certificate.go
pkg/httpAuth/mtls/mtls.go
pkg/logging/logger.go
pkg/server/ecsCredentialsHandler.go
pkg/server/server.go

This PR attaches errors to logs in a more consistent way so they're handled well by custom loggers.

Replace `logging.Log.Error()` with `logging.LogError()`

---

extras/macos/etc/pf.conf

Currently, Weep's macOS configuration does not allow the metadata emulation service to be accessed via `localhost` and `169.254.169.254` simultaneously. This PR adds a line to `pf.conf` to make the service accessible from both addresses.

Update macOS pf config to support metadata address and localhost simultaneously

---

.pre-commit-config.yaml
pkg/server/baseHandler.go
pkg/server/credentialsHandler.go
pkg/server/ecsCredentialsHandler.go
pkg/server/middleware.go
pkg/server/middleware_test.go
pkg/util/util.go

The credentials are returned as a JSON object so update the content type
to match instead of text/plain.

Use application/json as content type when returning credentials

---

cmd/vars.go

The server command does not have a `--role` optional. It takes role as a positional argument instead.

Update serve docstring

---

build/build_package.sh

It seems that GoReleaser changed the output path for built binaries. This PR fixes the macOS packaging script based on the change.

Fix binary path for macOS package build

---

cmd/credential_process.go
cmd/vars.go
docs/weep_credential_process.md

Add a new flag `--pretty` to be used w/ `weep credential_process --generate` to output profiles in `~/.aws/config` in the "account_name-role_name" format instead of profiles named after the role ARNs, while maintaining existing flow for backwards compatibility.

Add optional "account_name-role_name" profile name generation instead of ARNs

---

cmd/serve.go
pkg/server/server.go

The `-A` or `--assume-role` flag worked only when serving ECS Credential Provider endpoint.
This PRs fixes this by also passing the `assumeRole` arg down when starting up serving function in IMDS context.

Fix assumeRole parameter passing
